### ISSUE TITLE
Allocation of tensors while training takes a lot of memory

### ISSUE THREAD

**Issue by kabirahuja2431** [kevinlu1211/SQuAD-Models#1]
Hii kevinlu1211, I was also trying to implement BIDAF model for CS224n Assignment 4. I completed my implementation but when I started training the model, it crashed due to exhausting the GPU's memory. I wanted to confirm from you whether it's a normal thing to happen for this model or I have a buggy implementation for the same. My GPU memory is about 4gb.

Thanks :)

**Comment by rawmarshmellows** [comment]
Yes, my GPU has 11GB but try reducing the batch size to 1. If it still has
GPU memory exhausted then maybe there is a bug in your implementation.

**Comment by kabirahuja2431** [comment]
Thanks :+1: I will give it a try.

**Comment by kabirahuja2431** [comment]
It worked... Thanks for your suggestion:)
Btw, I have flattened my context and question states by:

context_flat = tf.transpose(tf.contrib.layers.flatten(tf.transpose(context_aug,[3,1,2,0])),[1,0])
ques_flat = tf.transpose(tf.contrib.layers.flatten(tf.transpose(ques_aug,[3,1,2,0])),[1,0])

Do you think that this technique is buggy or memory extensive as compared to yours?
Thanks :+1:

**Comment by rawmarshmellows** [comment]
Don't think that it will matter, though the best way is to try both and see the results
